### PR TITLE
Added initial tests after refactor

### PR DESCRIPTION
**Pull request by dunnen**
Here's the tests from my original PR refactored. It supports the new layout and the tests directory structure was updated based on @roks0n's comment.

Coveraged dropped to 81% but these are only the original tests refactored for the new layout.
```
ark/__init__.py                  1      0   100%
ark/api/one/__init__.py          0      0   100%
ark/api/one/account.py          18      4    78%
ark/api/one/block.py            24      0   100%
ark/api/one/delegate.py         23      1    96%
ark/api/one/loader.py            8      0   100%
ark/api/one/peers.py             8      0   100%
ark/api/one/signature.py         6      1    83%
ark/api/one/transaction.py      12      2    83%
ark/api/one/transport.py        27      4    85%
ark/api/one/vote.py              6      2    67%
ark/api/resource.py             13      4    69%
ark/client.py                   26      1    96%
ark/connection.py               74     27    64%
------------------------------------------------
TOTAL                          246     46    81%

```

There are 7 failures in transport with the error `AttributeError: 'Transport' object has no attribute 'connection'`.  I might need to set up the test differently now.

### CODE REVIEW

**Comment by dunnen** [comment]
According to travis-ci, the refactored code only works in python 3.6. It looks like it has trouble importing the api dynamically in 3.4 and 3.5.

**Comment by dunnen** [comment]
The `AttributeError: 'Transport' object has no attribute 'connection'` failures in Transport are because __init__() is being overridden. The code currently looks like this:

```
class Transport(Resource):
    def __init__(self, client):
        self.client = client
        self.client.port = 4002
```

I think it should be set to this:
```
class Transport(Resource):
    def __init__(self, client):
        super().__init__(connection)
        self.connection.port = 4002
```

Is someone able to confirm this is the correct answer?
